### ISSUE TITLE
Change JQuery requests to fetch

### ISSUE THREAD

**Issue by itsmeimtom** [itsmeimtom/itsmeimtom.github.io#12]
https://github.com/mrdnomaid/mrdnomaid.github.io/blob/48018852931180c635e78ca7d4772bafdc6b6c21/js/pages/404.js#L13

**Comment by tomfishemoji** [comment]
gotta test the issue features

**Comment by itsmeimtom** [comment]
"fixed" in https://github.com/itsmeimtom/itsmeimtom.github.io/commit/669056113254550d50ba1a1d7fff1c456a132cd3
